/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CcLoader {}
  interface CcLoaderAttributes extends StencilHTMLAttributes {}

  interface CcSideDrawer {
    'close': () => void;
    'open': () => void;
    'opened': boolean;
    'title': string;
  }
  interface CcSideDrawerAttributes extends StencilHTMLAttributes {
    'opened'?: boolean;
    'title'?: string;
  }

  interface CcStockPrice {
    'stockSymbol': string;
  }
  interface CcStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }

  interface CcToolTip {
    'title': string;
  }
  interface CcToolTipAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CcLoader': Components.CcLoader;
    'CcSideDrawer': Components.CcSideDrawer;
    'CcStockPrice': Components.CcStockPrice;
    'CcToolTip': Components.CcToolTip;
  }

  interface StencilIntrinsicElements {
    'cc-loader': Components.CcLoaderAttributes;
    'cc-side-drawer': Components.CcSideDrawerAttributes;
    'cc-stock-price': Components.CcStockPriceAttributes;
    'cc-tool-tip': Components.CcToolTipAttributes;
  }


  interface HTMLCcLoaderElement extends Components.CcLoader, HTMLStencilElement {}
  var HTMLCcLoaderElement: {
    prototype: HTMLCcLoaderElement;
    new (): HTMLCcLoaderElement;
  };

  interface HTMLCcSideDrawerElement extends Components.CcSideDrawer, HTMLStencilElement {}
  var HTMLCcSideDrawerElement: {
    prototype: HTMLCcSideDrawerElement;
    new (): HTMLCcSideDrawerElement;
  };

  interface HTMLCcStockPriceElement extends Components.CcStockPrice, HTMLStencilElement {}
  var HTMLCcStockPriceElement: {
    prototype: HTMLCcStockPriceElement;
    new (): HTMLCcStockPriceElement;
  };

  interface HTMLCcToolTipElement extends Components.CcToolTip, HTMLStencilElement {}
  var HTMLCcToolTipElement: {
    prototype: HTMLCcToolTipElement;
    new (): HTMLCcToolTipElement;
  };

  interface HTMLElementTagNameMap {
    'cc-loader': HTMLCcLoaderElement
    'cc-side-drawer': HTMLCcSideDrawerElement
    'cc-stock-price': HTMLCcStockPriceElement
    'cc-tool-tip': HTMLCcToolTipElement
  }

  interface ElementTagNameMap {
    'cc-loader': HTMLCcLoaderElement;
    'cc-side-drawer': HTMLCcSideDrawerElement;
    'cc-stock-price': HTMLCcStockPriceElement;
    'cc-tool-tip': HTMLCcToolTipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
